### PR TITLE
Add specific custom field parsing as ansible groups

### PR DESCRIPTION
**Pull request by Atoms**
In netbox add custom field ansible_groups fill in as comma seperated value, and each string is ansible_group.

### CODE REVIEW

**Comment by AAbouZaid** [comment]
@Atoms Could you please clarify the purpose of this PR?
What is its goal and what it should achieve?

Thanks.

**Comment by Atoms** [comment]
So if you want to add more groups to server, as we use server with groups such as service and many more, so if someone needs additional multiple groups for host, then create ansible_groups custom field in netbox and add there comma seperated groups for host.

**Comment by AAbouZaid** [comment]
Aha, got it.

Even I'd like to see it as Netbox feature ([Enable free-form, searchable, labeling/tagging of devices #132](https://github.com/digitalocean/netbox/issues/132)), but it's not there yet.

Anyway, I think a better way to do that instead hard coding it, let' use the [conf file](https://github.com/AAbouZaid/netbox-as-ansible-inventory/blob/master/netbox/netbox.yml) to to make it more flexible.

e.g.
```
netbox:
    main:
        custom_groups:
            key: ansible_groups
            separator: ","
```

**Comment by rthomson** [comment]
I'm also interested in exactly this functionality and agree that it would be best implemented in netbox itself with either free-form tagging on any level of object, tag fields or multi-select fields.

A custom field separator, defined in the config file would be useful but perhaps duplicate effort if netbox implements tags relatively soon.

**Comment by madkiss** [comment]
Folks, what is the current status of this? :)

**Comment by Atoms** [comment]
From my side no status updates, as it's not merged, we already maintain own tree with very specific additions and so on. so if @AAbouZaid is not merging this i would close this. and i see that this is already behind actual version

**Comment by AAbouZaid** [comment]
I will do some changes and back to it, since it seems Netbox project is not going to make it soon.

**Comment by Atoms** [comment]
seems noone cares, so closing PR

**Comment by aabouzaid** [comment]
Since now Netbox already has free-form of labeling/tagging so no need for this workaround anymore.
But anyways, thanks @Atoms for your effort :-)

**Pull request closed without merging**
